services:
   cece74.sharethis.listener:
        class: cece74\nivoslider\event\listener
        arguments:
            - @template
            - @dbal.conn
            - %core.table_prefix%
            - %core.root_path%
        tags:
            - { name: event.listener }
